appender.console.type = Console
appender.console.name = ConsoleAppender
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} [%t] %-5level %logger{36} - %msg%n

rootLogger.level = warn
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = ConsoleAppender

logger.application.name = lt.jonas.homework
logger.application.level = info
logger.application.additivity = false
logger.application.appenderRefs = console
logger.application.appenderRef.console.ref = ConsoleAppender
